const data = {
  products: [
    {
      name: 'Zoro Hoodie',
      slug: 'Zoro-Sweater',
      category: 'Sweaters',
      image: '/images/P1.jpg',
      price: 99.99,
      countInStock: 10,
      brand: 'PortalFashion',
      rating: 5,
      numReviews: 4,
      description: 'Wano Zoro Embroidarded Sweater: Two Tone Purple',
    },
    {
      name: 'Marco Hoodie',
      slug: 'Marco-Sweater',
      category: 'Sweaters',
      image: '/images/P2.jpg',
      price: 99.99,
      countInStock: 10,
      brand: 'PortalFashion',
      rating: 5,
      numReviews: 4,
      description: 'Marco Embroidarded Sweater: Light-Blue',
    },
    {
      name: 'Trafalger Law Shirt',
      slug: 'Trafalger-Law-Sweater',
      category: 'T-Shirts',
      image: '/images/P3.jpg',
      price: 35.99,
      countInStock: 10,
      brand: 'PortalFashion',
      rating: 5,
      numReviews: 4,
      description: 'Trafalger Law Embroidarded T-Shirt: Brown',
    },
    {
      name: 'Shanks Law Shirt',
      slug: 'Shanks-T-Shirts',
      category: 'T-Shirts',
      image: '/images/P4.jpg',
      price: 35.99,
      countInStock: 10,
      brand: 'PortalFashion',
      rating: 2,
      numReviews: 4,
      description: 'Shanks Embroidarded T-Shirts: Red',
    },
  ],
};

export default data;
